GCLOUD_PROJECT: nih-nci-dceg-connect-dev
GCLOUD_BUCKET: connect_firestore_dev_backup
GCLOUD_SENDGRID_SECRET: projects/nih-nci-dceg-connect-dev/secrets/sendgrid/versions/1
GCLOUD_SENDGRID_EMAIL_VALIDATION_SECRET: projects/nih-nci-dceg-connect-dev/secrets/sendgrid-email-validation/versions/1
GCLOUD_SENDGRID_EVENT_WEBHOOKSECRET: projects/nih-nci-dceg-connect-dev/secrets/sendgrid-event-webhook-verification-key/versions/1
SG_FROM_NAME: Connect for Cancer Prevention Study (DEV)
SG_FROM_EMAIL: donotreply@myconnect.cancer.gov
TWILIO_ACCOUNT_SID: projects/nih-nci-dceg-connect-dev/secrets/twilio-account-sid/versions/1
TWILIO_AUTH_TOKEN: projects/nih-nci-dceg-connect-dev/secrets/twilio-sms-auth-token/versions/1
TWILIO_MESSAGING_SERVICE_SID: projects/nih-nci-dceg-connect-dev/secrets/twilio-messaging-service-sid/versions/1
TWILIO_NOTIFY_SERVICE_SID: projects/nih-nci-dceg-connect-dev/secrets/twilio-notify-service-sid/versions/1
APP_REGISTRATION_TENANT_ID: projects/nih-nci-dceg-connect-dev/secrets/app-registration-tenant-id/versions/1
APP_REGISTRATION_CLIENT_ID: projects/nih-nci-dceg-connect-dev/secrets/app-registration-client-id/versions/1
APP_REGISTRATION_CLIENT_SECRET: projects/nih-nci-dceg-connect-dev/secrets/app-registration-client-secret/versions/2
GITHUB_TOKEN: projects/nih-nci-dceg-connect-dev/secrets/questionnaire-sha-tracking/versions/1